### ISSUE TITLE
Missing legacy paint-brush

### ISSUE THREAD

**Issue by sn4k3** [Projektanker/Icons.Avalonia#20]
I notice one missing legacy icon from my app

`paint-brush` is now `paintbrush`

https://fontawesome.com/v5/icons/paint-brush?s=solid
https://fontawesome.com/v6/icons/paintbrush?s=solid

Thanks for the amazing back support

**Comment by SebastianRumohr** [comment]
That's odd.  
I copied all renamed icons from [icons-renamed-in-version-6](https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6)

Anyway I added the legacy support for `paint-brush`. Thanks for reporting.

Fixed with [5.0.2](https://www.nuget.org/packages/Projektanker.Icons.Avalonia.FontAwesome/5.0.2)
